http-server:
  address: "localhost"                 #Адресс развёртывания HTTP сервера
  port: 8080
  timeout: 15s
  path-file-server: "./web/"  #путь до файлов фронта
  state: "auth1111"

postgres:
  host: "localhost"           #Адрес сервера PostgresSQL
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: ""

mongo:
  host: "localhost"           #Адрес сервера MongoDB
  port: 27017
  dbname: ""

logger:
  path: "log/log.txt"         #Путь до файла логов
  rang: "Debug"               #Debug|Info|Error|Off
